### ISSUE TITLE
Please take care of problematic symbolism ...

### ISSUE THREAD

**Issue by lskh** [LukeSmithxyz/wallpapers#3]
Just stumbled across these two, while browsing through this amazing collection:

Etc/f_mountain.png and
Etc/f_sunset.jpg

depict the "black sun" symbol, used by neo-nazis. https://en.wikipedia.org/wiki/Black_Sun_(symbol)
I think they should be deleted from the collection.

**Comment by jzbor** [comment]
Yeah I totally agree and would like to add the 4chan fascism symbols, which are even labled as something like chanfasc.jpg, so it doesnt really look like an accident...

**Comment by neilsimp1** [comment]
reichstag.png is literally swastika flags.

**Comment by lskh** [comment]
unbookmarked, unfollowed, unstarred ...

**Comment by sys-3** [comment]
Luke is being willfully ignorant to this...

**Comment by safaci2000** [comment]
as fun as this conversation is, have you tried doing a PR if you find some of the content objectionable?

**Comment by geremachek** [comment]
lol

**Comment by yarnrav** [comment]
> Hates Degeneracy
> Has nude lady pics 
lmao.

**Comment by Chexier** [comment]
> Hates Degeneracy
> Has nude lady pics
> Has videogames

Luke Smith exposed! Basedd11!! redpilled.

**Comment by yarnrav** [comment]
*Videogames are for consoomers*

**Comment by lskh** [comment]
I think this leads nowhere ...

**Comment by geremachek** [comment]
lol
